- id: forbid-swap-file
  name: 'forbid to commit swap file'
  entry: forbid-swap-file.sh
  files: '^\..*\.sw[a-zA-Z]$'
  language: "script"
  description: 'forbid to commit swap file, such as .foo.swp'
- id: check-commit-user-name-email
  name: 'check the commit user name and email'
  entry: check-commit-user-name-email.sh
  files: '^$'
  language: "script"
  always_run: true
  description: 'check the commit user name and email match the origin or not'
- id: forbid-binary
  name: 'forbid to commit binary file'
  entry: forbid-binary.sh
  language: script
  types: ['binary']
- id: post-commit-to-sqlite3
  name: 'post commit message to sqlite3'
  entry: post-commit-to-sqlite3.sh
  language: "script"
  always_run: true
  description: 'post commit message to sqlite3'
  stages: ['post-commit']
